CONTROLLER_KNOB_DIAMETER = 18.5;
CONTROLLER_KNOB_HEIGHT = 3.7;

FOOT_WALL_WIDTH = 1.5;
FOOT_NOSE_WIDTH = 1;
FOOT_NOSE_HEIGHT = 1;

GRIP_WIDTH = 2;
GRIP_ROUNDING = 1;

GRIP_SAUSAGE_LENGTH_STRONG = 14;
GRIP_SAUSAGE_LENGTH_SLIGHT = 12;

GRIP_CIRCULAR_PROTRUSION_STRONG = 1.2;
GRIP_CIRCULAR_PROTRUSION_SLIGHT = 0.7;
