CONTROLLER_XBOX_KNOB_DIAMETER = 18.5;
CONTROLLER_XBOX_KNOB_HEIGHT = 3.7;
CONTROLLER_PS4_KNOB_DIAMETER = 19.6;
CONTROLLER_PS4_KNOB_HEIGHT = 3.5;

FOOT_WALL_WIDTH = 1.5;
FOOT_NOSE_WIDTH = 1;
FOOT_NOSE_HEIGHT = 1;

GRIP_WIDTH = 2;
GRIP_ROUNDING = 1;

GRIP_SAUSAGE_LENGTH_BOLD = 14;
GRIP_SAUSAGE_LENGTH_LIGHT = 12;

GRIP_CIRCULAR_PROTRUSION_BOLD = 1.2;
GRIP_CIRCULAR_PROTRUSION_LIGHT = 0.7;
