CONTROLLER_XBOX_KNOB_DIAMETER = 18.5;
CONTROLLER_XBOX_KNOB_HEIGHT = 3.7;
CONTROLLER_PS4_KNOB_DIAMETER = 19.8;
CONTROLLER_PS4_KNOB_HEIGHT = 3.7;

FOOT_WALL_WIDTH = 1.5;
FOOT_NOSE_WIDTH = 1;
FOOT_NOSE_HEIGHT = 1;

GRIP_WIDTH = 2;
GRIP_ROUNDING = 1;

GRIP_SAUSAGE_LENGTH = 14;
GRIP_CIRCULAR_PROTRUSION = 0.7;